import type { Metadata } from "next";
import "./globals.css";

import Navbar from "./sections/Navbar";

export const metadata: Metadata = {
  title: "Osman Janjua",
  description: "Generated by Osman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
